name: Playwright Cucumber Tests

on:
  push:
    branches: [ flightbooking ]
  pull_request:
    branches: [ flightbooking ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Cucumber Tests
        run: npm run test:cucumber

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: test-results/reports/